print('Welcom to "SAU"', end='')
print("Welcom to 'DTI'", end="")
print("---------------")
print('Wwlcom to \'SAU\'')
print("Welcom to \"DTI\"")
print("-------------------")
print(4546)
print(4547.0545)
print(True)
print(False)
print(15 * 10 + 2) # expression นิพจน์
print(True or False and False)
